import "../globals.css";
import Navbar from "@/components/Navbar";
import NewsLetter from "@/components/NewsLetter";
import Footer from "@/components/Footer";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "All category",
  description: "Generated by create next app",
};

export default function CategoryLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <header className="h-[500px] bg-center flex flex-col-reverse bg-cover w-full bg-[url('/header.webp')]"></header>
        <main>
          {children}
          <NewsLetter />
        </main>
        <Footer />
      </body>
    </html>
  );
}
